import React, { useState, useEffect, useRef, useMemo } from 'react';
import { buildStationLineDirections } from '../utils/layoutHelpers';
/**
 * Helper utility to identify whether a station object is a 'D' class station.
 * 'D' class stations (like DXD or Kota) act as central hubs where lines connect 
 * straight through (e.g., Line 3 to Line 2) rather than using diagonal slant tracks.
 * 
 * @param {Object} stnObj - The station object from layout data
 * @returns {boolean} True if station is class 'D', false otherwise.
 */
const isDClass = (stnObj) => {
  if (!stnObj) return false;
  return String(stnObj.macclassflag || '').trim().toUpperCase() === 'D';
};

/**
 * StationLayout is the primary visualizer component for rendering the physical 
 * topology of railway tracks, platforms, and block sections. 
 * It takes structural layout data and draws an SVG-based map that includes 
 * zooming, panning, minimap navigation, and track hovering.
 * 
 * @param {Object} layout - The structured layout generated by StationLayoutTab
 * @param {string} scrollToStation - Optional station code to automatically scroll into view
 * @param {number} navTrigger - A numeric trigger to force navigation updates
 */
const TRACK_LINE_WIDTH = 4;

export default function StationLayout({ layout, scrollToStation, navTrigger, onModifyLayout }) {
  const [minimapHoverCode, setMinimapHoverCode] = useState(null);
  const [hoveredLine, setHoveredLine] = useState(null);
  const [activeTab, setActiveTab] = useState('layout');
  const scrollContainerRef = useRef(null);

  const [highlightedStation, setHighlightedStation] = useState(null);
  const highlightTimeoutRef = useRef(null);

  const [contextMenu, setContextMenu] = useState({
    visible: false,
    x: 0,
    y: 0,
    type: '',
    lineData: null,
    data: null
  });

  const [connectingState, setConnectingState] = useState(null);

  const handleLineClick = (e, type, lineData) => {
    e.stopPropagation();
    if (!connectingState) {
      setConnectingState({ type, lineData });
    } else {
      if (connectingState.type === type) {
        if (connectingState.lineData === lineData) {
          // Clicked the same line again, cancel connection
          setConnectingState(null);
        } else {
          // Clicked another line of same type, switch source
          setConnectingState({ type, lineData });
        }
      } else {
        // Valid connection target!
        const source = connectingState;
        const target = { type, lineData };
        if (onModifyLayout) {
          onModifyLayout('connection', 'add-connection', null, { source, target });
        }
        setConnectingState(null);
      }
    }
  };

  const tooltipRef = useRef(null);
  const [hoverTooltip, setHoverTooltip] = useState({
    visible: false,
    type: null,
    lineData: null
  });


  const hoverTooltipTimeoutRef = useRef(null);

  const updateTooltipPosition = (clientX, clientY) => {
    if (!tooltipRef.current) return;
    let x = clientX + 15;
    let y = clientY + 15;
    const rect = tooltipRef.current.getBoundingClientRect();
    if (x + rect.width > window.innerWidth) x = clientX - rect.width - 15;
    if (y + rect.height > window.innerHeight) y = clientY - rect.height - 15;
    tooltipRef.current.style.transform = `translate3d(${x}px, ${y}px, 0)`;
  };

  const showTooltip = (e, type, lineData) => {
    setHoveredLine(lineData);
    setHoverTooltip({ visible: true, type, lineData });
    requestAnimationFrame(() => updateTooltipPosition(e.clientX, e.clientY));
    if (hoverTooltipTimeoutRef.current) clearTimeout(hoverTooltipTimeoutRef.current);
    hoverTooltipTimeoutRef.current = setTimeout(() => {
      setHoverTooltip(prev => ({ ...prev, visible: false }));
    }, 5000);
  };

  const hideTooltip = () => {
    setHoveredLine(null);
    setHoverTooltip(prev => ({ ...prev, visible: false }));
    if (hoverTooltipTimeoutRef.current) clearTimeout(hoverTooltipTimeoutRef.current);
  };

  const [lineSettings, setLineSettings] = useState({});

  const getSettingsKey = (type, lineData) => {
    if (!lineData) return null;
    if (type.includes('station') || type === 'station') {
      const code = lineData.stnCode || lineData.code;
      return code ? `station-${code}` : null;
    } else if (type.includes('block') || type === 'block') {
      const code = lineData.bsCode || lineData.code;
      return code ? `block-${code}` : null;
    }
    return null;
  };

  const toggleSetting = (type, lineData, settingKey, value, e) => {
    if (e) {
      e.stopPropagation();
    }
    if (!lineData) return;

    if (settingKey === 'signalling' && (type === 'block' || String(type).includes('block'))) {
      const code = lineData.bsCode || lineData.code;
      const val = value === 'Absolute' ? 'AB' : 'AUTO';
      if (onModifyLayout) {
        onModifyLayout('block', 'signalling', code, { signalling: val });
      }
      return;
    }

    const key = getSettingsKey(type, lineData);
    if (!key) return;

    setLineSettings(prev => {
      const current = prev[key] || {};

      return {
        ...prev,
        [key]: {
          ...current,
          [settingKey]: [value]
        }
      };
    });
  };

  const getSetting = (type, lineData, settingKey, value) => {
    if (settingKey === 'signalling' && (type === 'block' || String(type).includes('block'))) {
      const code = lineData.bsCode || lineData.code;
      const rawSig = String(layout?.blockSections?.[code]?.lines?.[0]?.MAVSIGNALLING || '').trim().toUpperCase();
      if (value === 'Auto') return rawSig === 'AUTO';
      if (value === 'Absolute') return rawSig !== 'AUTO';
    }

    const key = getSettingsKey(type, lineData);
    if (!key) return false;
    const currentVals = lineSettings[key]?.[settingKey] || [];
    return currentVals.includes(value);
  };

  useEffect(() => {
    const handleClick = () => {
      if (contextMenu.visible) {
        setContextMenu(prev => ({ ...prev, visible: false }));
      }
    };
    window.addEventListener('click', handleClick);
    return () => window.removeEventListener('click', handleClick);
  }, [contextMenu.visible]);

  const structureHash = useMemo(() => {
    if (!layout) return '';
    let hash = '';
    layout.sequence.forEach(n => {
      if (n.type === 'station') {
        const stn = layout.stations[n.code];
        hash += `S:${n.code}:`;
        if (stn && stn.lines) {
          hash += stn.lines.map(l => `${parseFloat(l.MANSEQNUMB)}-${String(l.MACLINECATEGORY).trim().toUpperCase()}`).join(',');
        }
        if (stn && stn.platforms) {
          hash += '|P:' + stn.platforms.map(p => `${p.MAVPLATFORMNUMB}-${p.MANSEQNUMB}-${p.MAVPFVPOSITION}-${p.MAVPFHPOSITION}`).join(',');
        }
      } else if (n.type === 'block') {
        const bs = layout.blockSections[n.code];
        hash += `B:${n.code}:`;
        if (bs && bs.lines) {
          hash += bs.lines.map(l => `${parseFloat(l.MANSEQNUMB)}-${String(l.MACLINECATEGORY).trim().toUpperCase()}`).join(',');
        }
      }
    });
    hash += '|C:' + (layout.connections ? layout.connections.length : 0);
    return hash;
  }, [layout]);

  // Pass layout directly, but only recalculate when structural hash changes!
  // This skips expensive geometry math when only attributes (Speed, Signalling) change.
  const renderData = useMemo(() => generateRenderData(layout), [structureHash, layout?.type, layout?.mainValue]);

  // Helper: returns true when a specific block section uses Absolute signalling.
  // Used for per-element rendering so that changing one section doesn't affect others.
  const isBlockAbsolute = (bsCode) => {
    if (!bsCode || !layout?.blockSections?.[bsCode]) return true; // default AB
    const sig = String(layout.blockSections[bsCode].lines?.[0]?.MAVSIGNALLING || '').trim().toUpperCase();
    return sig === 'AB' || sig === 'ABSOLUTE' || sig === '';
  };

  const stationNodes = layout.sequence.filter(n => n.type === 'station');
  const leftStnCode = stationNodes.length > 0 ? stationNodes[0].code : 'Start';
  const rightStnCode = stationNodes.length > 1 ? stationNodes[stationNodes.length - 1].code : (stationNodes.length > 0 ? stationNodes[0].code : 'End');

  const scrollRef = useRef(null);
  const [scrollPos, setScrollPos] = React.useState({ left: 0, top: 0, width: 0, height: 0 });
  const [portalTarget, setPortalTarget] = useState(null);

  useEffect(() => {
    // Poll until the portal target div is available in the DOM
    const tryFind = () => {
      const el = document.getElementById('detailed-route-portal');
      if (el) {
        setPortalTarget(el);
      } else {
        setTimeout(tryFind, 50);
      }
    };
    tryFind();
  }, []);



  useEffect(() => {
    const handleScroll = () => {
      if (scrollRef.current) {
        setScrollPos({
          left: scrollRef.current.scrollLeft,
          top: scrollRef.current.scrollTop,
          width: scrollRef.current.clientWidth,
          height: scrollRef.current.clientHeight
        });
      }
    };

    const el = scrollRef.current;
    if (el) {
      el.addEventListener('scroll', handleScroll);
      setTimeout(handleScroll, 100);
      window.addEventListener('resize', handleScroll);
    }
    return () => {
      if (el) el.removeEventListener('scroll', handleScroll);
      window.removeEventListener('resize', handleScroll);
    };
  }, []);

  useEffect(() => {
    if (navTrigger > 0 && scrollToStation && scrollRef.current) {
      setTimeout(() => {
        const targetElement = document.getElementById(`station-zone-${scrollToStation}`);
        if (targetElement) {
          targetElement.scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'nearest' });
          setHighlightedStation(scrollToStation);
          if (highlightTimeoutRef.current) {
            clearTimeout(highlightTimeoutRef.current);
          }
          highlightTimeoutRef.current = setTimeout(() => {
            setHighlightedStation(null);
          }, 5000);
        }
      }, 50);
    }
    return () => {
      if (highlightTimeoutRef.current) clearTimeout(highlightTimeoutRef.current);
    };
  }, [navTrigger, scrollToStation]);

  return (
    <div style={{ position: 'relative' }}>
      <div
        ref={scrollRef}
        className="svg-canvas-wrapper"
        style={{ overflowX: 'auto', overflowY: 'auto', maxHeight: '35vh', width: '100%', backgroundColor: '#f8fafc', position: 'relative', borderRadius: '12px' }}
      >
        <svg
          width={Math.max(renderData.totalWidth * 0.65, 1000)}
          height={renderData.totalHeight * 0.65 + 40}
          className="drop-shadow-sm"
          style={{ backgroundColor: '#f8fafc', display: 'block', backgroundImage: 'radial-gradient(circle at 50% 50%, #ffffff 0%, #f1f5f9 100%)' }}
        >
          <defs>
            <marker id="arrowBlue" markerWidth="24" markerHeight="24" refX="20" refY="12" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 2 4 L 20 12 L 2 20 L 6 12 z" fill="#2563eb" />
            </marker>
            <marker id="arrowOrange" markerWidth="24" markerHeight="24" refX="20" refY="12" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 2 4 L 20 12 L 2 20 L 6 12 z" fill="#ea580c" />
            </marker>
            <marker id="arrowGrey" markerWidth="24" markerHeight="24" refX="20" refY="12" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 2 4 L 20 12 L 2 20 L 6 12 z" fill="#cbd5e1" />
            </marker>
            <marker id="arrowBi" markerWidth="24" markerHeight="24" refX="20" refY="12" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 2 4 L 20 12 L 2 20 L 6 12 z" fill="#10b981" />
            </marker>

            <marker id="arrowBlueMain" markerWidth="36" markerHeight="36" refX="16.5" refY="18" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 2 4 L 20 12 L 2 20 L 6 12 z" fill="#2563eb" transform="scale(1.5)" />
            </marker>
            <marker id="arrowOrangeMain" markerWidth="36" markerHeight="36" refX="16.5" refY="18" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 2 4 L 20 12 L 2 20 L 6 12 z" fill="#ea580c" transform="scale(1.5)" />
            </marker>
            <marker id="arrowGreyMain" markerWidth="36" markerHeight="36" refX="16.5" refY="18" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 2 4 L 20 12 L 2 20 L 6 12 z" fill="#cbd5e1" transform="scale(1.5)" />
            </marker>
            <marker id="arrowBiMain" markerWidth="36" markerHeight="36" refX="16.5" refY="18" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 2 4 L 20 12 L 2 20 L 6 12 z" fill="#10b981" transform="scale(1.5)" />
            </marker>
            <filter id="glow" x="-20%" y="-20%" width="140%" height="140%">
              <feGaussianBlur stdDeviation="4" result="blur" />
              <feComposite in="SourceGraphic" in2="blur" operator="over" />
            </filter>
            <filter id="glow-strong" x="-20%" y="-20%" width="140%" height="140%">
              <feGaussianBlur stdDeviation="6" result="blur" />
              <feComponentTransfer in="blur" result="glow">
                <feFuncA type="linear" slope="1.5" />
              </feComponentTransfer>
              <feComposite in="SourceGraphic" in2="glow" operator="over" />
            </filter>
            <filter id="shadow" x="-10%" y="-10%" width="120%" height="120%">
              <feDropShadow dx="0" dy="4" stdDeviation="4" floodColor="#94a3b8" floodOpacity="0.5" />
            </filter>
            <linearGradient id="stationBg" x1="0%" y1="0%" x2="0%" y2="100%">
              <stop offset="0%" stopColor="rgba(255, 255, 255, 0.95)" />
              <stop offset="100%" stopColor="rgba(241, 245, 249, 0.95)" />
            </linearGradient>
            <linearGradient id="railGrad" x1="0%" y1="0%" x2="0%" y2="100%">
              <stop offset="0%" stopColor="#475569" />
              <stop offset="50%" stopColor="#94a3b8" />
              <stop offset="100%" stopColor="#475569" />
            </linearGradient>
            <pattern id="sleepers" width="12" height="16" patternUnits="userSpaceOnUse">
              <rect x="2" y="0" width="8" height="16" fill="#334155" rx="2" />
            </pattern>
            <pattern id="concrete" width="16" height="16" patternUnits="userSpaceOnUse">
              <rect width="16" height="16" fill="#e2e8f0" />
              <circle cx="4" cy="4" r="1.5" fill="#cbd5e1" />
              <circle cx="12" cy="12" r="1" fill="#cbd5e1" />
              <circle cx="4" cy="12" r="1.5" fill="#f8fafc" opacity="0.5" />
              <circle cx="12" cy="4" r="1" fill="#f8fafc" opacity="0.5" />
            </pattern>
            <linearGradient id="railGradOrange" x1="0%" y1="0%" x2="0%" y2="100%">
              <stop offset="0%" stopColor="#c2410c" />
              <stop offset="50%" stopColor="#ea580c" />
              <stop offset="100%" stopColor="#c2410c" />
            </linearGradient>
            <pattern id="sleepersOrange" width="12" height="16" patternUnits="userSpaceOnUse">
              <rect x="2" y="0" width="8" height="16" fill="#ea580c" rx="2" />
            </pattern>
            <linearGradient id="railGradBlue" x1="0%" y1="0%" x2="0%" y2="100%">
              <stop offset="0%" stopColor="#1e40af" />
              <stop offset="50%" stopColor="#2563eb" />
              <stop offset="100%" stopColor="#1e40af" />
            </linearGradient>
            <pattern id="sleepersBlue" width="12" height="16" patternUnits="userSpaceOnUse">
              <rect x="2" y="0" width="8" height="16" fill="#2563eb" rx="2" />
            </pattern>
          </defs>

          <g transform="scale(0.65)">
            {renderData.stationZones.map((z, i) => {
              const isHighlighted = highlightedStation === z.code;
              return (
                <g key={`zone-${i}`} id={`station-zone-${z.code}`} style={{ transition: 'all 0.3s ease' }}>
                  <rect
                    x={z.x} y={z.y} width={z.w} height={z.h}
                    fill={isHighlighted ? "#fef3c7" : "url(#stationBg)"}
                    rx="16"
                    stroke={isHighlighted ? "#f59e0b" : "#93c5fd"}
                    strokeWidth={isHighlighted ? "4" : "1.5"}
                    strokeOpacity="0.8"
                    style={{ transition: 'all 0.3s ease' }}
                  />
                  <path d={`M ${z.x + 16} ${z.y} L ${z.x + z.w - 16} ${z.y}`} stroke={isHighlighted ? "#d97706" : "#3b82f6"} strokeWidth="2" opacity="0.8" />
                  <text x={z.x + z.w / 2} y={z.y + 20} fill={isHighlighted ? "#92400e" : "#1e293b"} fontSize="16" fontWeight="800" textAnchor="middle" letterSpacing="1">
                    {z.code} {z.macclassflag ? `(${z.macclassflag})` : ''} / {z.MAVDVSNCODE}
                  </text>
                  <rect x={z.x + z.w / 2 - 70} y={z.y + 26} width="140" height="20" rx="10" fill={isHighlighted ? "#fde68a" : "#f1f5f9"} stroke={isHighlighted ? "#f59e0b" : "#cbd5e1"} />
                  <text x={z.x + z.w / 2} y={z.y + 40} fill={isHighlighted ? "#92400e" : "#475569"} fontSize="10" fontWeight="bold" textAnchor="middle">
                    {z.name}
                  </text>
                  <text x={z.x + z.w / 2} y={z.y + 56} fill={isHighlighted ? "#b45309" : "#64748b"} fontSize="10" fontWeight="500" textAnchor="middle">
                    ({z.MANMILEPOSTKM_I}/{z.MANMILEPOSTSUBKM_I} {z.MAVREFSTTN_I})
                  </text>
                </g>
              )
            })}


            {renderData.mainLineTracks.map((trk, i) => {
              const dx = Math.sin(trk.angle) * 5;
              const dy = Math.cos(trk.angle) * 5;
              const sleepersFill = trk.trackColor === 'orange' ? "url(#sleepersOrange)" : trk.trackColor === 'blue' ? "url(#sleepersBlue)" : "url(#sleepers)";
              const railFill = trk.trackColor === 'orange' ? "url(#railGradOrange)" : trk.trackColor === 'blue' ? "url(#railGradBlue)" : "url(#railGrad)";
              // Per-track signalling: look up the block section this track belongs to.
              // Avoids the old isGlobalAbsolute that changed ALL tracks when ONE section changed.
              const trkIsAbsolute = isBlockAbsolute(trk.bsCode);
              return (
                <g key={`mlt-${i}`}>
                  {trkIsAbsolute ? (
                    <>
                      <line x1={trk.x1} y1={trk.y1} x2={trk.x2} y2={trk.y2} stroke={trk.trackColor === 'orange' ? '#ea580c' : trk.trackColor === 'blue' ? '#2563eb' : '#64748b'} strokeWidth={TRACK_LINE_WIDTH} opacity="1" />
                    </>
                  ) : (
                    <>
                      <line x1={trk.x1} y1={trk.y1} x2={trk.x2} y2={trk.y2} stroke={sleepersFill} strokeWidth={TRACK_LINE_WIDTH} opacity="0.9" />
                      <line x1={trk.x1 - dx} y1={trk.y1 - dy} x2={trk.x2 - dx} y2={trk.y2 - dy} stroke={railFill} strokeWidth="1" />
                      <line x1={trk.x1 + dx} y1={trk.y1 + dy} x2={trk.x2 + dx} y2={trk.y2 + dy} stroke={railFill} strokeWidth="1" />
                    </>
                  )}
                </g>
              )
            })}

            {renderData.stationLines.map((sl, i) => (
              <g
                key={`sl-${i}`}
                pointerEvents="all"
                onMouseEnter={(e) => showTooltip(e, 'station', sl)}
                onMouseMove={(e) => {
                  updateTooltipPosition(e.clientX, e.clientY);
                  if (hoverTooltipTimeoutRef.current) clearTimeout(hoverTooltipTimeoutRef.current);
                  hoverTooltipTimeoutRef.current = setTimeout(() => setHoverTooltip(prev => ({ ...prev, visible: false })), 5000);
                }}
                onMouseLeave={hideTooltip}
                onClick={(e) => handleLineClick(e, 'station', sl)}
                onContextMenu={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  setContextMenu({
                    visible: true,
                    x: e.clientX,
                    y: e.clientY,
                    type: 'station-line',
                    lineData: sl,
                    data: { code: sl.stnCode }
                  });
                }}
                style={{ cursor: connectingState ? 'crosshair' : 'pointer' }}
              >
                {connectingState?.lineData === sl && (
                  <line x1={sl.x1} y1={sl.y} x2={sl.x2} y2={sl.y} stroke="#fcd34d" strokeWidth="28" opacity="0.8" />
                )}
                {isBlockAbsolute(sl.adjacentBsCode) ? (
                  // Absolute signalling: filled rect, no stroke border, no shadow
                  <line x1={sl.x1} y1={sl.y} x2={sl.x2} y2={sl.y} stroke={sl.trackColor === 'orange' ? '#ea580c' : sl.trackColor === 'blue' ? '#2563eb' : '#64748b'} strokeWidth={TRACK_LINE_WIDTH} opacity="1" />
                ) : (
                  // Auto signalling: thinner sleepers + two rails, no drop-shadow filter
                  <>
                    <line x1={sl.x1} y1={sl.y} x2={sl.x2} y2={sl.y} stroke={sl.trackColor === 'orange' ? "url(#sleepersOrange)" : sl.trackColor === 'blue' ? "url(#sleepersBlue)" : "url(#sleepers)"} strokeWidth={TRACK_LINE_WIDTH} opacity="0.9" />
                    <line x1={sl.x1} y1={sl.y - 1} x2={sl.x2} y2={sl.y - 1} stroke={sl.trackColor === 'orange' ? "url(#railGradOrange)" : sl.trackColor === 'blue' ? "url(#railGradBlue)" : "url(#railGrad)"} strokeWidth="1" />
                    <line x1={sl.x1} y1={sl.y + 1} x2={sl.x2} y2={sl.y + 1} stroke={sl.trackColor === 'orange' ? "url(#railGradOrange)" : sl.trackColor === 'blue' ? "url(#railGradBlue)" : "url(#railGrad)"} strokeWidth="1" />
                  </>
                )}
              </g>
            ))}

            {renderData.blockLines.map((bl, i) => {
              const isAutoSignalling = String(layout?.blockSections?.[bl.bsCode]?.lines?.[0]?.MAVSIGNALLING || '').trim().toUpperCase() === 'AUTO';
              const solidFill = bl.trackColor === 'orange' ? '#ea580c' : bl.trackColor === 'blue' ? '#2563eb' : '#475569';
              const solidFillLight = bl.trackColor === 'orange' ? '#fed7aa' : bl.trackColor === 'blue' ? '#bfdbfe' : '#cbd5e1';
              return (
                <g
                  key={`bl-${i}`}
                  pointerEvents="all"
                  onMouseEnter={(e) => showTooltip(e, 'block', bl)}
                  onMouseMove={(e) => {
                    updateTooltipPosition(e.clientX, e.clientY);
                    if (hoverTooltipTimeoutRef.current) clearTimeout(hoverTooltipTimeoutRef.current);
                    hoverTooltipTimeoutRef.current = setTimeout(() => setHoverTooltip(prev => ({ ...prev, visible: false })), 5000);
                  }}
                  onMouseLeave={hideTooltip}
                  onClick={(e) => handleLineClick(e, 'block', bl)}
                  onContextMenu={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                  }}
                  style={{ cursor: connectingState ? 'crosshair' : 'pointer' }}
                >
                  {connectingState?.lineData === bl && (
                    <line x1={bl.x1} y1={bl.y} x2={bl.x2} y2={bl.y} stroke="#fcd34d" strokeWidth="28" opacity="0.8" />
                  )}
                  {isAutoSignalling ? (
                    /* Auto Signalling: thinner sleepers + two rails, no drop-shadow filter */
                    <>
                      <line x1={bl.x1} y1={bl.y} x2={bl.x2} y2={bl.y} stroke={bl.trackColor === 'orange' ? "url(#sleepersOrange)" : bl.trackColor === 'blue' ? "url(#sleepersBlue)" : "url(#sleepers)"} strokeWidth={TRACK_LINE_WIDTH} opacity="0.8" />
                      <line x1={bl.x1} y1={bl.y - 1} x2={bl.x2} y2={bl.y - 1} stroke={bl.trackColor === 'orange' ? "url(#railGradOrange)" : bl.trackColor === 'blue' ? "url(#railGradBlue)" : "url(#railGrad)"} strokeWidth="1" />
                      <line x1={bl.x1} y1={bl.y + 1} x2={bl.x2} y2={bl.y + 1} stroke={bl.trackColor === 'orange' ? "url(#railGradOrange)" : bl.trackColor === 'blue' ? "url(#railGradBlue)" : "url(#railGrad)"} strokeWidth="1" />
                    </>
                  ) : (
                    /* Absolute Signalling: filled rect, no stroke border, no shadow */
                    <rect
                      x={bl.x1}
                      y={bl.y - 5}
                      width={bl.x2 - bl.x1}
                      height={10}
                      rx="2"
                      fill={solidFillLight}
                      opacity="0.92"
                    />
                  )}
                </g>
              );
            })}

            {renderData.connections.map((c, i) => {
              let arrowId = "arrowGrey";
              let mainArrowId = "arrowGreyMain";
              if (c.color === '#ea580c') {
                arrowId = "arrowOrange";
                mainArrowId = "arrowOrangeMain";
              } else if (c.color === '#2563eb') {
                arrowId = "arrowBlue";
                mainArrowId = "arrowBlueMain";
              }

              return (
                <g
                  key={`conn-${i}`}
                  onDoubleClick={(e) => {
                    e.stopPropagation();
                    if (onModifyLayout) onModifyLayout('connection', 'delete', c.rawConn);
                  }}
                  style={{ cursor: 'pointer' }}
                >
                  {c.isBidirectional ? (
                    <path
                      d={c.path}
                      stroke={c.isRedundantMainLine ? "transparent" : c.color}
                      strokeWidth="4"
                      strokeLinejoin="round"
                      fill="none"
                      opacity="0.9"
                      markerMid={c.isRedundantMainLine ? "url(#arrowBiMain)" : "none"}
                      markerStart={c.isRedundantMainLine ? "none" : "url(#arrowBi)"}
                      markerEnd={c.isRedundantMainLine ? "none" : "url(#arrowBi)"}
                    />
                  ) : (
                    <path
                      d={c.path}
                      stroke={c.isRedundantMainLine ? "transparent" : c.color}
                      strokeWidth="4"
                      strokeLinejoin="round"
                      fill="none"
                      opacity="0.9"
                      markerMid={c.isRedundantMainLine ? `url(#${mainArrowId})` : "none"}
                      markerEnd={c.isRedundantMainLine ? "none" : `url(#${arrowId})`}
                    />
                  )}
                </g>
              );
            })}

            {renderData.distances.map((d, i) => (
              <g key={`dist-${i}`}>
                <path d={`M ${d.x1} ${d.y} L ${d.x1} ${d.y + 12} M ${d.x2} ${d.y} L ${d.x2} ${d.y + 12} M ${d.x1} ${d.y + 6} L ${d.x2} ${d.y + 6}`} stroke="#475569" strokeWidth="2" opacity="0.8" />
                <rect x={(d.x1 + d.x2) / 2 - 25} y={d.y - 4} width="50" height="20" fill="#ffffff" rx="4" stroke="#cbd5e1" strokeWidth="1.5" />
                <text x={(d.x1 + d.x2) / 2} y={d.y + 10} fill="#1d4ed8" fontSize="12" textAnchor="middle" fontWeight="bold" letterSpacing="1">{d.dist} km</text>
              </g>
            ))}

            {renderData.platforms.map((pf, i) => (
              <g key={`pf-${i}`} >
                <rect x={pf.x} y={pf.y} width={pf.w} height={pf.h} fill="url(#concrete)" stroke="#94a3b8" strokeWidth="2" rx="4" />
                <rect
                  x={pf.x + 2}
                  y={(pf.isUp ? pf.y + pf.h - 2 : pf.y + 2) - 1.25}
                  width={Math.max(0, pf.w - 4)}
                  height={2.5}
                  fill="#fbbf24"

                />
                <rect x={pf.x + pf.w - 45} y={pf.y + pf.h / 2 - 7} width="40" height="14" fill="#ffffff" rx="7" stroke="#f59e0b" strokeWidth="1.5" />
                <text x={pf.x + pf.w - 25} y={pf.y + pf.h / 2 + 4} fill="#b45309" fontSize="11" fontWeight="900" textAnchor="middle">{pf.label}</text>
              </g>
            ))}

            {renderData.stationLines.map((sl, i) => (
              <g
                key={`sl-lbl-${i}`}

                pointerEvents="all"
                onContextMenu={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                }}
              >
                <rect x={(sl.x1 + sl.x2) / 2 - 28} y={sl.y - 8} width="56" height="16" rx="8" fill={sl.trackColor === 'orange' ? "#fff7ed" : sl.trackColor === 'blue' ? "#eff6ff" : "#ffffff"} stroke={sl.trackColor === 'orange' ? "#ea580c" : sl.trackColor === 'blue' ? "#2563eb" : "#cbd5e1"} strokeWidth="1" />
                <text x={(sl.x1 + sl.x2) / 2} y={sl.y + 4} fill={sl.trackColor === 'orange' ? "#ea580c" : sl.trackColor === 'blue' ? "#2563eb" : "#475569"} fontSize="11" fontWeight="bold" textAnchor="middle" style={{ pointerEvents: 'none' }}>{sl.label}</text>
              </g>
            ))}
            {renderData.blockLines.map((bl, i) => (
              <g
                key={`bl-lbl-${i}`}

                pointerEvents="all"
                onContextMenu={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                }}
                style={{ cursor: 'default' }}
              >
                <rect x={(bl.x1 + bl.x2) / 2 - 28} y={bl.y - 8} width="56" height="16" rx="8" fill={bl.trackColor === 'orange' ? "#fff7ed" : bl.trackColor === 'blue' ? "#eff6ff" : "#ffffff"} stroke={bl.trackColor === 'orange' ? "#ea580c" : bl.trackColor === 'blue' ? "#2563eb" : "#cbd5e1"} strokeWidth="1" />
                <text x={(bl.x1 + bl.x2) / 2} y={bl.y + 4} fill={bl.trackColor === 'orange' ? "#ea580c" : bl.trackColor === 'blue' ? "#2563eb" : "#475569"} fontSize="11" fontWeight="bold" textAnchor="middle" style={{ pointerEvents: 'none' }}>{bl.label}</text>
              </g>
            ))}

            {renderData.labels.map((lb, i) => (
              <g
                key={`lb-${i}`}
                filter={lb.isStation ? "url(#glow)" : undefined}
                pointerEvents="all"
                onContextMenu={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  setContextMenu({
                    visible: true,
                    x: e.clientX,
                    y: e.clientY,
                    type: lb.isStation ? 'station-name' : 'block-name',
                    data: lb
                  });
                }}
                style={{ cursor: 'context-menu' }}
              >
                <text x={lb.x} y={lb.y + 12} fill="#1e293b" fontSize={lb.size} fontWeight="900" textAnchor="middle" letterSpacing="1">
                  {lb.text}
                </text>
              </g>
            ))}
          </g>
        </svg>
      </div>

      {/* Minimap logic removed */}

      {contextMenu.visible && (
        <div
          style={{
            position: 'fixed',
            top: contextMenu.y,
            left: contextMenu.x,
            backgroundColor: '#ffffff',
            boxShadow: '0 10px 25px rgba(0,0,0,0.2)',
            borderRadius: '8px',
            border: '1px solid #cbd5e1',
            padding: '8px 0',
            zIndex: 9999,
            minWidth: '160px',
            fontSize: '14px',
            color: '#1e293b'
          }}
          onContextMenu={(e) => e.preventDefault()}
        >
          <style>{`
            .ctx-menu-hover:hover { background-color: #f1f5f9; color: #2563eb; }
            .ctx-menu-item:hover .ctx-submenu { display: block !important; }
          `}</style>
          <div style={{ padding: '4px 16px', borderBottom: '1px solid #e2e8f0', marginBottom: '4px', fontWeight: 'bold', color: '#64748b', fontSize: '12px' }}>
            {contextMenu.type.includes('name') ?
              (contextMenu.type === 'block-name' ? `Block Section: ${contextMenu.data?.text || contextMenu.data?.code}` : `Station: ${contextMenu.data?.name || contextMenu.data?.code}`)
              :
              `${contextMenu.type.includes('block') ? 'Block Section Line' : 'Station Line'} ${contextMenu.lineData?.label}`
            }
          </div>

          {contextMenu.type === 'block' && (
            <>
              <div style={{ padding: '6px 16px', cursor: 'pointer', color: '#dc2626' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('block', 'delete', contextMenu.lineData); setContextMenu({ ...contextMenu, visible: false }); }}>
                Delete Main Line
              </div>
            </>
          )}

          {contextMenu.type === 'block-name' && (
            <>
              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', color: '#16a34a', fontWeight: '500' }} className="ctx-menu-hover">
                  Add Main Line <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '120px', display: 'none'
                }}>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => {
                    const name = window.prompt("Enter Block Section Line Name:");
                    if (name) {
                      const lines = layout.blockSections[contextMenu.data?.code]?.lines || [];
                      const exists = lines.some(l => String(l.MAVLINENUMB).trim() === name.trim() || String(l.MANSEQNUMB).trim() === name.trim());
                      if (exists) {
                        window.alert("Duplicate name. This line already exists.");
                      } else {
                        if (onModifyLayout) onModifyLayout('block', 'add', contextMenu.data?.code, { position: 'top', direction: 'BOTH', lineName: name });
                      }
                    }
                    setContextMenu({ ...contextMenu, visible: false });
                  }}>Top</div>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => {
                    const name = window.prompt("Enter Block Section Line Name:");
                    if (name) {
                      const lines = layout.blockSections[contextMenu.data?.code]?.lines || [];
                      const exists = lines.some(l => String(l.MAVLINENUMB).trim() === name.trim() || String(l.MANSEQNUMB).trim() === name.trim());
                      if (exists) {
                        window.alert("Duplicate name. This line already exists.");
                      } else {
                        if (onModifyLayout) onModifyLayout('block', 'add', contextMenu.data?.code, { position: 'bottom', direction: 'BOTH', lineName: name });
                      }
                    }
                    setContextMenu({ ...contextMenu, visible: false });
                  }}>Bottom</div>
                </div>
              </div>

              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between' }} className="ctx-menu-hover">
                  Signalling <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '120px', display: 'none'
                }}>
                  {[{ label: 'Absolute', val: 'AB' }, { label: 'Auto', val: 'AUTO' }].map(sig => (
                    <div key={sig.val} style={{ padding: '6px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '8px' }} className="ctx-menu-hover" onClick={(e) => {
                      if (onModifyLayout) onModifyLayout('block', 'signalling', contextMenu.data?.code, { signalling: sig.val });
                      setContextMenu({ ...contextMenu, visible: false });
                      e.stopPropagation();
                    }}>
                      <span>{sig.label}</span>
                      <input type="radio" checked={String(layout.blockSections[contextMenu.data?.code]?.lines?.[0]?.MAVSIGNALLING).trim().toUpperCase() === sig.val} readOnly style={{ cursor: 'pointer', accentColor: '#10b981' }} />
                    </div>
                  ))}
                </div>
              </div>

              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between' }} className="ctx-menu-hover">
                  Speed <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '120px', display: 'none', maxHeight: '200px', overflowY: 'auto'
                }}>
                  {[30, 45, 50, 60, 75, 90, 100, 110, 130, 160].map(s => (
                    <div key={s} style={{ padding: '6px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '8px' }} className="ctx-menu-hover" onClick={(e) => {
                      if (onModifyLayout) onModifyLayout('block', 'speed', contextMenu.data, { speed: s });
                      setContextMenu({ ...contextMenu, visible: false });
                      e.stopPropagation();
                    }}>
                      <span>{s} kmph</span>
                      <input type="radio" checked={String(layout.blockSections[contextMenu.data?.code]?.lines?.[0]?.MAVSPEED) === String(s)} readOnly style={{ cursor: 'pointer', accentColor: '#10b981' }} />
                    </div>
                  ))}
                </div>
              </div>

              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', color: '#dc2626', fontWeight: '500' }} className="ctx-menu-hover">
                  Delete Main Lines <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '160px', display: 'none'
                }}>
                  {(layout.blockSections[contextMenu.data?.code]?.lines || []).map((line, idx) => {
                    const label = line.MAVLINENUMB || line.MANSEQNUMB;

                    return (
                      <div key={idx} style={{ padding: '6px 16px', cursor: 'pointer', color: '#dc2626' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('block', 'delete', { originalLine: line, code: contextMenu.data.code }); setContextMenu({ ...contextMenu, visible: false }); }}>
                        {label}
                      </div>
                    );
                  })}
                  {(layout.blockSections[contextMenu.data?.code]?.lines || []).length === 0 && (
                    <div style={{ padding: '6px 16px', color: '#94a3b8', fontStyle: 'italic', fontSize: '11px' }}>No lines</div>
                  )}
                </div>
              </div>

            </>
          )}

          {contextMenu.type === 'block-label' && (
            <>
              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between' }} className="ctx-menu-hover">
                  Signalling <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '120px', display: 'none'
                }}>
                  <div style={{ padding: '6px 16px', cursor: 'pointer', display: 'flex', flexDirection: 'column', gap: '4px' }} className="ctx-menu-hover" onClick={(e) => toggleSetting(contextMenu.type, contextMenu.lineData, 'signalling', 'Absolute', e)}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '8px', width: '100%' }}>
                      <span>Absolute</span>
                      <input type="radio" checked={getSetting(contextMenu.type, contextMenu.lineData, 'signalling', 'Absolute')} readOnly style={{ cursor: 'pointer', accentColor: '#10b981' }} />
                    </div>
                    <div style={{ fontSize: '10px', color: '#64748b', fontStyle: 'italic' }}>
                      Max {Math.max(1, Math.ceil((parseFloat(layout.sequence?.find(n => n.type === 'block' && n.code === contextMenu.data?.code)?.distance) || 0) / 3.6))} trains (3.6km spacing)
                    </div>
                  </div>
                  <div style={{ padding: '6px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '8px' }} className="ctx-menu-hover" onClick={(e) => toggleSetting(contextMenu.type, contextMenu.lineData, 'signalling', 'Auto', e)}>
                    <span>Auto</span>
                    <input type="radio" checked={getSetting(contextMenu.type, contextMenu.lineData, 'signalling', 'Auto')} readOnly style={{ cursor: 'pointer', accentColor: '#10b981' }} />
                  </div>
                </div>
              </div>

              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between' }} className="ctx-menu-hover">
                  Speed <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '120px', display: 'none'
                }}>
                  {[60, 90, 100, 110, 130, 160].map(s => (
                    <div key={s} style={{ padding: '6px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '8px' }} className="ctx-menu-hover" onClick={(e) => {
                      if (onModifyLayout) {
                        onModifyLayout(contextMenu.type.includes('block') ? 'block' : 'station', 'loopspeed', contextMenu.lineData, { speed: s });
                      }
                      setContextMenu({ ...contextMenu, visible: false });
                      e.stopPropagation();
                    }}>
                      <span>{s} kmph</span>
                      <input type="radio" checked={String(contextMenu.lineData?.originalLine?.MAVSPEED) === String(s)} readOnly style={{ cursor: 'pointer', accentColor: '#10b981' }} />
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}

          {contextMenu.type === 'station-line' && (
            <>
              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', color: '#16a34a', fontWeight: '500' }} className="ctx-menu-hover">
                  Add Platform <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '120px', display: 'none'
                }}>
                  {(() => {
                    const stnCode = contextMenu.data?.code;
                    const seqNum = parseFloat(contextMenu.lineData?.originalLine?.MANSEQNUMB);
                    const pfs = layout.stations[stnCode]?.platforms?.filter(p => parseFloat(p.MANSEQNUMB) === seqNum) || [];
                    const upPfs = pfs.filter(p => p.MAVPFVPOSITION === 'U');
                    const downPfs = pfs.filter(p => p.MAVPFVPOSITION === 'D');

                    const renderDirOptions = (vPos, label, existingPfs, isFirst) => {
                      const count = existingPfs.length;
                      if (count >= 3) return null; // Max platforms reached for this side

                      const allStationPfs = layout.stations[stnCode]?.platforms || [];
                      const handleAdd = (hPos, promptText, e) => {
                        const name = window.prompt(promptText);
                        if (name) {
                          const exists = allStationPfs.some(p => String(p.MAVPLATFORMNUMB).trim() === name.trim());
                          if (exists) {
                            window.alert("already exist and please choose another");
                          } else {
                            if (onModifyLayout) onModifyLayout('station', 'add-platform', contextMenu.lineData, { vPos: vPos === 'Up' ? 'U' : 'D', hPos, platformName: name });
                          }
                        }
                        setContextMenu({ ...contextMenu, visible: false });
                        e.stopPropagation();
                      };

                      const header = (
                        <div style={{ padding: '4px 16px', fontSize: '11px', fontWeight: 'bold', color: '#64748b', backgroundColor: '#f8fafc', borderBottom: '1px solid #e2e8f0', borderTop: isFirst ? 'none' : '1px solid #e2e8f0' }}>
                          {label}
                        </div>
                      );

                      let options = null;
                      if (count === 0) {
                        options = (
                          <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={(e) => handleAdd('M', `Enter name for new ${label} platform:`, e)}>
                            Add Platform
                          </div>
                        );
                      } else if (count === 1) {
                        options = (
                          <>
                            <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={(e) => handleAdd('L', `Enter name for Left platform:`, e)}>Left</div>
                            <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={(e) => handleAdd('R', `Enter name for Right platform:`, e)}>Right</div>
                          </>
                        );
                      } else if (count === 2) {
                        options = (
                          <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={(e) => handleAdd('M', `Enter name for Middle platform:`, e)}>Middle</div>
                        );
                      }

                      return (
                        <>
                          {header}
                          {options}
                        </>
                      );
                    };

                    const upOpts = renderDirOptions('Up', 'Up', upPfs, true);
                    const downOpts = renderDirOptions('Down', 'Down', downPfs, !upOpts);

                    return (
                      <>
                        {upOpts}
                        {downOpts}
                      </>
                    );
                  })()}
                </div>
              </div>

              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', color: '#dc2626', fontWeight: '500' }} className="ctx-menu-hover">
                  Delete Platform <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '120px', display: 'none'
                }}>
                  {(() => {
                    const stnCode = contextMenu.data?.code;
                    const seqNum = parseFloat(contextMenu.lineData?.originalLine?.MANSEQNUMB);
                    const pfs = layout.stations[stnCode]?.platforms?.filter(p => parseFloat(p.MANSEQNUMB) === seqNum) || [];

                    if (pfs.length === 0) {
                      return <div style={{ padding: '6px 16px', color: '#94a3b8', fontStyle: 'italic', fontSize: '11px' }}>No platforms</div>;
                    }

                    return pfs.map((pf, idx) => {
                      const posLabel = pf.MAVPFVPOSITION === 'U' ? 'Up' : 'Down';
                      const hPosLabel = pf.MAVPFHPOSITION === 'L' ? 'Left' : (pf.MAVPFHPOSITION === 'R' ? 'Right' : 'Middle');
                      return (
                        <div key={idx} style={{ padding: '6px 16px', cursor: 'pointer', color: '#dc2626', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '8px' }} className="ctx-menu-hover" onClick={(e) => {
                          if (onModifyLayout) onModifyLayout('station', 'delete-platform', contextMenu.lineData, { platform: pf });
                          setContextMenu({ ...contextMenu, visible: false });
                          e.stopPropagation();
                        }}>
                          <span>{pf.MAVPLATFORMNUMB}</span>
                          <span style={{ fontSize: '10px', color: '#94a3b8' }}>{posLabel} {hPosLabel}</span>
                        </div>
                      );
                    });
                  })()}
                </div>
              </div>

              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', color: '#16a34a', fontWeight: '500' }} className="ctx-menu-hover">
                  Add Station Line <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '120px', display: 'none'
                }}>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => {
                    const name = window.prompt("Enter the name for the new station line:");
                    if (name) {
                      const stnCode = contextMenu.data?.code;
                      const lines = layout.stations[stnCode]?.lines || [];
                      const exists = lines.some(l => String(l.MAVLINENUMB).trim() === name.trim() || String(l.MANSEQNUMB).trim() === name.trim());
                      if (exists) {
                        window.alert("Already exists and choose another");
                      } else {
                        if (onModifyLayout) onModifyLayout('station', 'add', contextMenu.lineData, { position: 'up', direction: 'BOTH', lineName: name, targetSeq: contextMenu.lineData?.originalLine?.MANSEQNUMB });
                      }
                    }
                    setContextMenu({ ...contextMenu, visible: false });
                  }}>Up</div>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => {
                    const name = window.prompt("Enter the name for the new station line:");
                    if (name) {
                      const stnCode = contextMenu.data?.code;
                      const lines = layout.stations[stnCode]?.lines || [];
                      const exists = lines.some(l => String(l.MAVLINENUMB).trim() === name.trim() || String(l.MANSEQNUMB).trim() === name.trim());
                      if (exists) {
                        window.alert("Already exists and choose another");
                      } else {
                        if (onModifyLayout) onModifyLayout('station', 'add', contextMenu.lineData, { position: 'down', direction: 'BOTH', lineName: name, targetSeq: contextMenu.lineData?.originalLine?.MANSEQNUMB });
                      }
                    }
                    setContextMenu({ ...contextMenu, visible: false });
                  }}>Down</div>
                </div>
              </div>

              <div style={{ padding: '6px 16px', cursor: 'pointer', color: '#dc2626' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('station', 'delete', contextMenu.lineData); setContextMenu({ ...contextMenu, visible: false }); }}>
                Delete Loop Line
              </div>

              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between' }} className="ctx-menu-hover">
                  Speed <span style={{ fontSize: '10px', marginTop: '2px' }}>▼</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '120px', display: 'none'
                }}>
                  {(() => {
                    const oLine = contextMenu.lineData?.originalLine || {};
                    const catStr = String(oLine.MACLINECATEGORY || '').trim().toUpperCase();
                    const seq = parseInt(oLine.MANSEQNUMB);
                    let isMain = false;
                    if (catStr === 'M' || catStr === 'MAIN') isMain = true;
                    else if (catStr === 'L' || catStr === 'LOOP') isMain = false;
                    else isMain = seq <= 2;

                    const speeds = isMain ? [60, 90, 100, 110, 130] : [15, 30, 45];
                    const title = isMain ? 'Main Line' : 'Loop Line';

                    return (
                      <>
                        <div style={{ padding: '4px 16px', fontSize: '11px', fontWeight: 'bold', color: '#64748b', background: '#f8fafc' }}>{title}</div>
                        {speeds.map(s => (
                          <div key={s} style={{ padding: '6px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '8px' }} className="ctx-menu-hover" onClick={(e) => {
                            if (onModifyLayout) onModifyLayout('station', 'speed', contextMenu.lineData, { speed: s, isMain: isMain });
                            setContextMenu({ ...contextMenu, visible: false });
                            e.stopPropagation();
                          }}>
                            <span>{s} kmph</span>
                            <input type="radio" checked={String(oLine.MAVSPEED) === String(s)} readOnly style={{ cursor: 'pointer', accentColor: '#10b981' }} />
                          </div>
                        ))}
                      </>
                    );
                  })()}
                </div>
              </div>
            </>
          )}

          {contextMenu.type === 'station' && (
            <>
              <div style={{ padding: '6px 16px', cursor: 'pointer', color: '#dc2626' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('station', 'delete', contextMenu.lineData); setContextMenu({ ...contextMenu, visible: false }); }}>
                Delete Loop Line
              </div>
            </>
          )}

          {contextMenu.type === 'station-name' && (
            <>
              <div className="ctx-menu-item" style={{ position: 'relative' }}>
                <div style={{ padding: '8px 16px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', color: '#16a34a', fontWeight: '500' }} className="ctx-menu-hover">
                  Add Loop Line <span style={{ fontSize: '10px', marginTop: '2px' }}>▶</span>
                </div>
                <div className="ctx-submenu" style={{
                  position: 'absolute', top: 0, left: '100%', backgroundColor: '#fff',
                  boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderRadius: '6px', border: '1px solid #cbd5e1', padding: '8px 0', minWidth: '160px', display: 'none'
                }}>
                  <div style={{ padding: '4px 16px', fontWeight: 'bold', fontSize: '11px', color: '#64748b', borderBottom: '1px solid #e2e8f0', marginBottom: '4px' }}>Add at Top</div>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('station', 'add', contextMenu.data, { position: 'top', direction: 'UP' }); setContextMenu({ ...contextMenu, visible: false }); }}>UP</div>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('station', 'add', contextMenu.data, { position: 'top', direction: 'DN' }); setContextMenu({ ...contextMenu, visible: false }); }}>DOWN</div>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('station', 'add', contextMenu.data, { position: 'top', direction: 'BOTH' }); setContextMenu({ ...contextMenu, visible: false }); }}>BOTH</div>

                  <div style={{ padding: '4px 16px', fontWeight: 'bold', fontSize: '11px', color: '#64748b', borderBottom: '1px solid #e2e8f0', marginBottom: '4px', marginTop: '8px' }}>Add at Bottom</div>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('station', 'add', contextMenu.data, { position: 'bottom', direction: 'UP' }); setContextMenu({ ...contextMenu, visible: false }); }}>UP</div>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('station', 'add', contextMenu.data, { position: 'bottom', direction: 'DN' }); setContextMenu({ ...contextMenu, visible: false }); }}>DOWN</div>
                  <div style={{ padding: '6px 16px', cursor: 'pointer' }} className="ctx-menu-hover" onClick={() => { if (onModifyLayout) onModifyLayout('station', 'add', contextMenu.data, { position: 'bottom', direction: 'BOTH' }); setContextMenu({ ...contextMenu, visible: false }); }}>BOTH</div>
                </div>
              </div>
            </>
          )}

        </div>
      )}
      {hoverTooltip.visible && hoverTooltip.lineData && (
        <div ref={tooltipRef}
          style={{
            position: 'fixed', top: 0, left: 0,
            backgroundColor: '#ffffff',
            boxShadow: '0 4px 15px rgba(0,0,0,0.15)',
            borderRadius: '6px',
            border: '1px solid #cbd5e1',
            padding: '8px 12px',
            zIndex: 9999,
            pointerEvents: 'none',
            fontSize: '12px',
            color: '#1e293b',
            whiteSpace: 'nowrap'
          }}
        >
          {(() => {
            const isBlock = hoverTooltip.type === 'block';
            const title = isBlock ? hoverTooltip.lineData.bsCode : hoverTooltip.lineData.stnCode;
            const lineName = hoverTooltip.lineData.label;

            if (isBlock) {
              const dynLine = layout?.blockSections?.[title]?.lines?.find(l => parseFloat(l.MANSEQNUMB) === hoverTooltip.lineData.seq) || hoverTooltip.lineData.originalLine || {};
              const sigRaw = String(dynLine.MAVSIGNALLING || 'None').trim();
              let sig = sigRaw || 'None';
              if (sigRaw.toUpperCase() === 'AB') sig = 'Absolute';
              if (sigRaw.toUpperCase() === 'AUTO') sig = 'Automatic';

              const spd = String(dynLine.MAVSPEED || 'None').trim();
              const spdStr = spd !== 'None' ? `${spd} kmph` : 'None';
              return (
                <>
                  <div style={{ fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '4px', marginBottom: '4px' }}>{title} ({lineName})</div>
                  <div>Signal: <span style={{ fontWeight: '500', color: '#2563eb' }}>{sig}</span></div>
                  <div>Speed: <span style={{ fontWeight: '500', color: '#16a34a' }}>{spdStr}</span></div>
                </>
              );
            } else {
              const dynLine = layout?.stations?.[title]?.lines?.find(l => parseFloat(l.MANSEQNUMB) === hoverTooltip.lineData.seq) || hoverTooltip.lineData.originalLine || {};
              const spd = String(dynLine.MAVSPEED || 'None').trim();
              const spdStr = spd !== 'None' ? `${spd} kmph` : 'None';

              return (
                <>
                  <div style={{ fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '4px', marginBottom: '4px' }}>{title} ({lineName})</div>
                  <div>Speed: <span style={{ fontWeight: '500', color: '#16a34a' }}>{spdStr}</span></div>
                </>
              );
            }
          })()}
        </div>
      )}
    </div>
  );
}

function generateRenderData(layout) {
  const data = {
    stationZones: [],
    stationLines: [],
    platforms: [],
    blockLines: [],
    connections: [],
    mainLineTracks: [],
    labels: [],
    distances: [],
    totalWidth: 800,
    totalHeight: 600
  };


  const ySpacing = 40;

  const lineEnds = {};

  const mainLineCache = {};
  const getMainLinesForNode = (code, type) => {
    const key = `${type}-${code}`;
    if (mainLineCache[key]) return mainLineCache[key];

    let lines = [];
    if (type === 'station') {
      const stn = layout.stations[code];
      if (stn && stn.lines) {
        lines = stn.lines.filter(l => {
          const cat = String(l.MACLINECATEGORY || '').trim().toUpperCase();
          return cat === 'M' || cat === 'MAIN';
        });
        if (lines.length === 0) {
          lines = stn.lines.filter(l => parseFloat(l.MANSEQNUMB) <= 2);
        }
      }
    } else {
      const bs = layout.blockSections[code];
      if (bs && bs.lines) {
        lines = bs.lines.filter(l => {
          const cat = String(l.MACLINECATEGORY || '').trim().toUpperCase();
          return cat === 'M' || cat === 'MAIN';
        });
        if (lines.length === 0) {
          lines = bs.lines.filter(l => {
            const cat = String(l.MACLINECATEGORY || '').trim().toUpperCase();
            return cat !== 'LOOP';
          });
        }
      }
    }

    lines.sort((a, b) => parseFloat(a.MANSEQNUMB) - parseFloat(b.MANSEQNUMB));
    mainLineCache[key] = lines;
    return lines;
  };

  const nodeIndexMap = {};
  layout.sequence.forEach((n, i) => {
    nodeIndexMap[n.code] = i;
  });

  const stationLineDirs = buildStationLineDirections(layout);

  const getLineColor = (line, nodeCode, nodeType, seqNum) => {
    if (nodeType === 'station') {
      const dir = stationLineDirs[nodeCode]?.[seqNum];
      if (dir === 'DOWN') return 'blue';
      if (dir === 'UP') return 'orange';
      return 'default';
    }
    // Block section coloring
    const bs = layout.blockSections[nodeCode];
    if (!bs) return 'default';
    let mLines = bs.lines.filter(l => {
      const cat = String(l.MACLINECATEGORY || '').trim().toUpperCase();
      return cat === 'M' || cat === 'MAIN';
    });
    if (mLines.length === 0) {
      mLines = bs.lines.filter(l => String(l.MACLINECATEGORY || '').trim().toUpperCase() !== 'LOOP');
    }
    mLines.sort((a, b) => parseFloat(a.MANSEQNUMB) - parseFloat(b.MANSEQNUMB));
    const mainLineIndex = mLines.findIndex(l => parseFloat(l.MANSEQNUMB) === parseInt(seqNum));

    // Check adjacent stations to infer block direction if possible, else fallback
    if (mainLineIndex === 0) return 'blue';
    if (mainLineIndex === 1) return 'orange';
    return 'default';
  };

  let currentX = 80;
  const blockWidth = 160;
  const stationWidth = 140;
  const gap = 120;

  const startY = 200;
  let maxBottomY = 0;
  let minTopY = 10000;

  const MAIN_Y_START = 400;

  layout.sequence.forEach((node) => {
    let nodeLines = [];
    if (node.type === 'station' && layout.stations[node.code]) {
      nodeLines = layout.stations[node.code].lines;
    } else if (node.type === 'block' && layout.blockSections[node.code]) {
      nodeLines = layout.blockSections[node.code].lines;
    }

    if (nodeLines.length > 0) {
      nodeLines.sort((a, b) => (parseFloat(a.MANSEQNUMB) || 0) - (parseFloat(b.MANSEQNUMB) || 0));

      let mainLineIndex = -1;
      const mLines = getMainLinesForNode(node.code, node.type);
      if (mLines.length > 0) {
        let anchorLine = mLines.find(l => {
          const seqNum = parseFloat(l.MANSEQNUMB);
          if (node.type === 'station') {
            return layout.connections.some(c => c.MAVSTTNCODE === node.code && parseFloat(c.MANSTTNLINENUMB) === seqNum);
          } else {
            return layout.connections.some(c => {
              let cBs = c.MAVBLCKSCTN || '';
              if (nodeIndexMap[cBs] === undefined) {
                const reversed = String(cBs).split('-').reverse().join('-');
                if (nodeIndexMap[reversed] !== undefined) cBs = reversed;
              }
              return cBs === node.code && parseFloat(c.MANBSLINENUMB) === seqNum;
            });
          }
        });
        if (!anchorLine) anchorLine = mLines[0];
        mainLineIndex = nodeLines.findIndex(l => parseFloat(l.MANSEQNUMB) === parseFloat(anchorLine.MANSEQNUMB));
      }
      if (mainLineIndex === -1) {
        mainLineIndex = 0; // fallback to first line if no main line found
      }

      nodeLines.forEach((l, index) => {
        const yPos = MAIN_Y_START + (index - mainLineIndex) * ySpacing;
        l.y = yPos;
        l.globalY = yPos; // For block sections
        l.lineIndex = index;
      });
    }
  });

  layout.sequence.forEach((node, nodeIdx) => {
    if (node.type === 'station') {
      const stnCode = node.code;
      const stn = layout.stations[stnCode];
      if (!stn) return;

      // Find an adjacent block section to inherit its signalling for the station line visuals.
      // Prefer the left neighbor; fall back to the right neighbor.
      let adjacentBsCode = null;
      const leftNeighbor = nodeIdx > 0 ? layout.sequence[nodeIdx - 1] : null;
      const rightNeighbor = nodeIdx < layout.sequence.length - 1 ? layout.sequence[nodeIdx + 1] : null;
      if (leftNeighbor && leftNeighbor.type === 'block') adjacentBsCode = leftNeighbor.code;
      else if (rightNeighbor && rightNeighbor.type === 'block') adjacentBsCode = rightNeighbor.code;

      let topY = stn.lines.length > 0 ? Math.min(...stn.lines.map(l => l.y)) : MAIN_Y_START;
      let bottomY = stn.lines.length > 0 ? Math.max(...stn.lines.map(l => l.y)) : MAIN_Y_START;

      if (bottomY + 50 > maxBottomY) maxBottomY = bottomY + 50;
      if (topY - 100 < minTopY) minTopY = topY - 100;

      data.stationZones.push({
        x: currentX - 10,
        y: topY - 95,
        w: stationWidth + 20,
        h: (bottomY - topY) + 140,
        name: stn.name || node.name || stnCode,
        code: stnCode,
        macclassflag: stn.macclassflag,
        MAVDVSNCODE: stn.MAVDVSNCODE,
        MANMILEPOSTKM_I: stn.MANMILEPOSTKM_I,
        MANMILEPOSTSUBKM_I: stn.MANMILEPOSTSUBKM_I,
        MAVREFSTTN_I: stn.MAVREFSTTN_I
      });

      stn.lines.forEach((line) => {
        const y = line.y;
        const x1 = currentX;
        const x2 = currentX + stationWidth;
        const seqNum = parseFloat(line.MANSEQNUMB);
        const lineNumb = line.MAVLINENUMB || seqNum;

        const trackColor = getLineColor(line, stnCode, 'station', seqNum);

        data.stationLines.push({ x1, x2, y, label: lineNumb, seq: seqNum, category: line.MACLINECATEGORY, lineIndex: line.lineIndex, trackColor, originalLine: line, stnCode, adjacentBsCode });
        lineEnds[`${stnCode}-LINE-${lineNumb}`] = { leftX: x1, rightX: x2, y, label: `L${lineNumb}`, trackColor };
        lineEnds[`${stnCode}-SEQ-${seqNum}`] = { leftX: x1, rightX: x2, y, label: `L${lineNumb}`, trackColor };
        lineEnds[`${stnCode}-ID-${String(line.MANSTTNLINENUMB).trim()}`] = { leftX: x1, rightX: x2, y, label: `L${lineNumb}`, trackColor };

        const pfs = stn.platforms.filter(p => parseFloat(p.MANSEQNUMB) === seqNum);
        pfs.forEach((pf) => {
          const isUp = pf.MAVPFVPOSITION === 'U';
          let pfW = stationWidth;
          let pfX = currentX;

          const sidePfs = pfs.filter(p => p.MAVPFVPOSITION === pf.MAVPFVPOSITION);
          const count = sidePfs.length;

          const sorted = [...sidePfs].sort((a, b) => {
            const weight = { 'L': 1, 'M': 2, 'R': 3 };
            return (weight[a.MAVPFHPOSITION || 'M'] || 2) - (weight[b.MAVPFHPOSITION || 'M'] || 2);
          });
          const idx = sorted.indexOf(pf);

          if (count === 1) {
            pfW = stationWidth;
            pfX = currentX;
          } else if (count === 2) {
            pfW = stationWidth / 2;
            if (idx === 0) {
              pfX = currentX;
            } else {
              pfX = currentX + stationWidth / 2;
            }
          } else {
            pfW = stationWidth / 3;
            if (idx === 0) {
              pfX = currentX;
            } else if (idx === 1) {
              pfX = currentX + stationWidth / 3;
            } else {
              pfX = currentX + (stationWidth * 2 / 3);
            }
          }

          data.platforms.push({
            x: pfX,
            y: isUp ? y - 20 : y + 5,
            w: pfW,
            h: 15,
            label: pf.MAVPLATFORMNUMB,
            isUp
          });
        });
      });
      currentX += stationWidth + gap;
    }
    else if (node.type === 'block') {
      const bsCode = node.code;
      const bs = layout.blockSections[bsCode];
      if (!bs) return;

      const centerX = currentX + blockWidth / 2;

      let topY = 10000;
      let bottomY = 0;
      if (bs.lines.length > 0) {
        topY = Math.min(...bs.lines.map(l => l.globalY));
        bottomY = Math.max(...bs.lines.map(l => l.globalY));
      }

      const idx = layout.sequence.indexOf(node);
      const prevNode = idx > 0 ? layout.sequence[idx - 1] : null;
      const nextNode = idx < layout.sequence.length - 1 ? layout.sequence[idx + 1] : null;

      let adjTopY = topY;
      if (prevNode && prevNode.type === 'station') {
        const pStn = layout.stations[prevNode.code];
        if (pStn && pStn.lines.length > 0) adjTopY = Math.min(adjTopY, ...pStn.lines.map(l => l.y));
      }
      if (nextNode && nextNode.type === 'station') {
        const nStn = layout.stations[nextNode.code];
        if (nStn && nStn.lines.length > 0) adjTopY = Math.min(adjTopY, ...nStn.lines.map(l => l.y));
      }

      data.labels.push({ text: bsCode, x: centerX, y: adjTopY - 35, size: 14, isStation: false, code: bsCode });

      if (bottomY + 45 > maxBottomY) maxBottomY = bottomY + 45;
      if (adjTopY - 45 < minTopY) minTopY = adjTopY - 45;

      bs.lines.forEach((line) => {
        const y = line.globalY;
        const x1 = currentX;
        const x2 = currentX + blockWidth;
        const seqNum = parseFloat(line.MANSEQNUMB);
        const lineNumb = line.MAVLINENUMB || seqNum;

        const trackColor = getLineColor(line, bsCode, 'block', seqNum);

        data.blockLines.push({ x1, x2, y, label: lineNumb, seq: seqNum, lineIndex: line.lineIndex, trackColor, originalLine: line, bsCode });
        lineEnds[`${bsCode}-LINE-${lineNumb}`] = { leftX: x1, rightX: x2, y, label: `L${lineNumb}`, trackColor };
        lineEnds[`${bsCode}-SEQ-${seqNum}`] = { leftX: x1, rightX: x2, y, label: `L${lineNumb}`, trackColor };
        lineEnds[`${bsCode}-ID-${String(line.MANBSLINENUMB).trim()}`] = { leftX: x1, rightX: x2, y, label: `L${lineNumb}`, trackColor };
      });

      let totalDist = parseFloat(node.distance) || 0;
      let blockDist = Math.max(0, totalDist - 1.0).toFixed(2);
      if (blockDist.endsWith('.00')) blockDist = blockDist.slice(0, -3);

      data.distances.push({
        x1: currentX + 10,
        x2: currentX + blockWidth - 10,
        y: bottomY + 40,
        dist: blockDist
      });

      currentX += blockWidth + gap;
    }
  });

  data.totalWidth = currentX + 40;

  const verticalOffset = 10 - minTopY;

  [data.stationZones, data.stationLines, data.platforms, data.blockLines, data.labels, data.distances].forEach(arr => {
    arr.forEach(item => { if (item.y !== undefined) item.y += verticalOffset; });
  });
  Object.values(lineEnds).forEach(le => { le.y += verticalOffset; });

  data.totalHeight = maxBottomY + verticalOffset + 30;

  layout.connections.forEach(conn => {
    const stnLineNum = parseInt(conn.MANSTTNLINENUMB);
    const bsLineNum = parseInt(conn.MANBSLINENUMB);

    if (isNaN(stnLineNum) || isNaN(bsLineNum)) return;

    let bsCode = conn.MAVBLCKSCTN || '';
    const checkBSExists = (code, num, raw) => {
      if (lineEnds[`${code}-ID-${String(raw).trim()}`]) return true;
      if (!isNaN(num) && lineEnds[`${code}-SEQ-${num}`]) return true;
      if (lineEnds[`${code}-LINE-${String(raw).trim()}`]) return true;
      return false;
    };

    if (!checkBSExists(bsCode, bsLineNum, conn.MANBSLINENUMB)) {
      const reversed = String(bsCode).split('-').reverse().join('-');
      if (checkBSExists(reversed, bsLineNum, conn.MANBSLINENUMB)) {
        bsCode = reversed;
      } else {
        return;
      }
    }

    let stnLine = lineEnds[`${conn.MAVSTTNCODE}-ID-${String(conn.MANSTTNLINENUMB).trim()}`];
    if (!stnLine && !isNaN(stnLineNum)) stnLine = lineEnds[`${conn.MAVSTTNCODE}-SEQ-${stnLineNum}`];
    if (!stnLine) stnLine = lineEnds[`${conn.MAVSTTNCODE}-LINE-${String(conn.MANSTTNLINENUMB).trim()}`];

    let bsLine = lineEnds[`${bsCode}-ID-${String(conn.MANBSLINENUMB).trim()}`];
    if (!bsLine && !isNaN(bsLineNum)) bsLine = lineEnds[`${bsCode}-SEQ-${bsLineNum}`];
    if (!bsLine) bsLine = lineEnds[`${bsCode}-LINE-${String(conn.MANBSLINENUMB).trim()}`];


    if (stnLine && bsLine) {
      let startX, startY = stnLine.y;
      let endX, endY = bsLine.y;

      const stnCenterX = (stnLine.leftX + stnLine.rightX) / 2;
      const bsCenterX = (bsLine.leftX + bsLine.rightX) / 2;

      if (bsCenterX > stnCenterX) {
        startX = stnLine.rightX;
        endX = bsLine.leftX;
      } else {
        startX = stnLine.leftX;
        endX = bsLine.rightX;
      }

      const isSend = conn.MACRECVSENDFLAG === 'S';
      const isBidirectional = conn.MACRECVSENDFLAG === 'B';
      const isMSync = conn.MACRECVSENDFLAG === 'M_SYNC';

      const isLeftToRight = (bsCenterX > stnCenterX && (isSend || isMSync)) || (bsCenterX < stnCenterX && !(isSend || isMSync));

      const offset = (isBidirectional || isMSync) ? 0 : (isSend ? -5 : 5);
      const adjStartY = startY + offset;
      const adjEndY = endY + offset;

      const midX = (startX + endX) / 2;
      const midY = (adjStartY + adjEndY) / 2;

      let path;
      if (isSend || isBidirectional || isMSync) {
        path = `M ${startX} ${adjStartY} L ${midX} ${midY} L ${endX} ${adjEndY}`;
      } else {
        path = `M ${endX} ${adjEndY} L ${midX} ${midY} L ${startX} ${adjStartY}`;
      }

      const actualStnLine = layout.stations[conn.MAVSTTNCODE]?.lines.find(l => parseFloat(l.MANSEQNUMB) === stnLineNum);
      const isMSyncType = conn.MACCONNECTNTYPE === 'M';

      const stnCat = actualStnLine ? String(actualStnLine.MACLINECATEGORY || '').trim().toUpperCase() : '';
      const isMainLineConnection = isMSync || isMSyncType || stnCat === 'M' || stnCat === 'MAIN';

      let adjacentStnIsDClass = false;
      const stnCode = conn.MAVSTTNCODE;

      if (layout.stations[stnCode] && layout.stations[stnCode].macclassflag === 'D') {
        adjacentStnIsDClass = true;
      } else {
        const bsIndex = layout.sequence.findIndex(n => n.code === bsCode);
        if (bsIndex !== -1) {
          const prevStn = layout.sequence[bsIndex - 1];
          const nextStn = layout.sequence[bsIndex + 1];
          if (prevStn && prevStn.type === 'station' && layout.stations[prevStn.code]?.macclassflag === 'D') {
            adjacentStnIsDClass = true;
          }
          if (nextStn && nextStn.type === 'station' && layout.stations[nextStn.code]?.macclassflag === 'D') {
            adjacentStnIsDClass = true;
          }
        }
      }

      const stnL = stnLine.label;
      const bsL = bsLine.label;
      let isUnwantedSlant = false;
      if (adjacentStnIsDClass) {
        if ((stnL === 'L2' && bsL === 'L1') || (stnL === 'L1' && bsL === 'L2')) {
          isUnwantedSlant = true;
        }
      }

      if (!isUnwantedSlant) {
        const mLinesStn = getMainLinesForNode(conn.MAVSTTNCODE, 'station');
        const mLinesBs = getMainLinesForNode(bsCode, 'block');

        const stnMainIdx = mLinesStn.findIndex(l => parseFloat(l.MANSEQNUMB) === stnLineNum);
        const bsMainIdx = mLinesBs.findIndex(l => parseFloat(l.MANSEQNUMB) === bsLineNum);

        const isRedundantMainLine = (stnMainIdx !== -1 && bsMainIdx !== -1 && stnMainIdx === bsMainIdx);

        let connectionColor = (isLeftToRight ? '#2563eb' : '#ea580c');
        if (isBidirectional || isMSync) {
          connectionColor = '#10b981'; // Green for sync
        }

        data.connections.push({
          rawConn: conn,
          path,
          startX, startY, endX, endY,
          color: connectionColor,
          isLeftToRight,
          isBidirectional: isBidirectional || isMSync,
          isMainLineConnection,
          isRedundantMainLine,
          label: (isBidirectional || isMSync) ? `${stnLine.label} ↔ ${bsLine.label}` : isSend ? `${stnLine.label} → ${bsLine.label}` : `${stnLine.label} ← ${bsLine.label}`
        });
      }
    }
  });

  layout.sequence.forEach((node, i) => {
    if (i === layout.sequence.length - 1) return;
    const nextNode = layout.sequence[i + 1];

    const getLines = (n) => {
      let lines = [];
      if (n.type === 'station') {
        const stn = layout.stations[n.code];
        if (stn) {
          lines = stn.lines.filter(l => {
            const cat = String(l.MACLINECATEGORY || '').trim().toUpperCase();
            return cat === 'M' || cat === 'MAIN';
          });
        }
        if (lines.length === 0 && stn) lines = stn.lines.filter(l => parseFloat(l.MANSEQNUMB) <= 2);
      } else {
        const bs = layout.blockSections[n.code];
        if (bs) {
          lines = bs.lines.filter(l => {
            const cat = String(l.MACLINECATEGORY || '').trim().toUpperCase();
            return cat === 'M' || cat === 'MAIN';
          });
          if (lines.length === 0) {
            lines = bs.lines.filter(l => {
              const cat = String(l.MACLINECATEGORY || '').trim().toUpperCase();
              return cat !== 'LOOP';
            });
          }
        }
      }
      return lines;
    };

    const linesA = getLines(node).sort((a, b) => parseFloat(a.MANSEQNUMB) - parseFloat(b.MANSEQNUMB));
    const linesB = getLines(nextNode).sort((a, b) => parseFloat(a.MANSEQNUMB) - parseFloat(b.MANSEQNUMB));

    const maxLen = Math.max(linesA.length, linesB.length);
    for (let j = 0; j < maxLen; j++) {
      const la = linesA[j];
      const lb = linesB[j];
      if (!la || !lb) continue;

      const leA = lineEnds[`${node.code}-SEQ-${parseFloat(la.MANSEQNUMB)}`];
      const leB = lineEnds[`${nextNode.code}-SEQ-${parseFloat(lb.MANSEQNUMB)}`];

      if (leA && leB) {
        let startX, endX, startY = leA.y, endY = leB.y;
        if (leB.leftX > leA.rightX) {
          startX = leA.rightX; endX = leB.leftX;
        } else {
          startX = leA.leftX; endX = leB.rightX;
        }

        const angle = Math.atan2(endY - startY, endX - startX);

        let isUnwantedSlantTrack = false;
        let adjacentStnIsDClass = false;

        const isD = (code) => layout.stations[code] && layout.stations[code].macclassflag === 'D';

        if (node.type === 'station' && isD(node.code)) adjacentStnIsDClass = true;
        if (nextNode.type === 'station' && isD(nextNode.code)) adjacentStnIsDClass = true;

        if (node.type === 'block') {
          const prevStnIdx = layout.sequence.findIndex(s => s.code === node.code) - 1;
          if (prevStnIdx >= 0 && layout.sequence[prevStnIdx].type === 'station' && isD(layout.sequence[prevStnIdx].code)) {
            adjacentStnIsDClass = true;
          }
        }
        if (nextNode.type === 'block') {
          const nextStnIdx = layout.sequence.findIndex(s => s.code === nextNode.code) + 1;
          if (nextStnIdx < layout.sequence.length && layout.sequence[nextStnIdx].type === 'station' && isD(layout.sequence[nextStnIdx].code)) {
            adjacentStnIsDClass = true;
          }
        }

        if (adjacentStnIsDClass) {
          if ((leA.label === 'L2' && leB.label === 'L1') || (leA.label === 'L1' && leB.label === 'L2')) {
            isUnwantedSlantTrack = true;
          }
        }

        if (!isUnwantedSlantTrack) {
          let trackColor = leA.trackColor || 'default';
          // Attach the block section code so the renderer can do per-track signalling lookup.
          // The track spans from node → nextNode; pick the block node (one of the two).
          const bsCode = node.type === 'block' ? node.code : (nextNode.type === 'block' ? nextNode.code : null);

          data.mainLineTracks.push({
            x1: startX, y1: startY, x2: endX, y2: endY, angle, trackColor, bsCode
          });
        }
      }
    }
  });


  data.distances.forEach(d => {
    let localBottomY = 0;
    data.blockLines.forEach(bl => {
      if (bl.x1 <= d.x2 && bl.x2 >= d.x1) {
        if (bl.y > localBottomY) localBottomY = bl.y;
      }
    });
    data.mainLineTracks.forEach(mlt => {
      const minX = Math.min(mlt.x1, mlt.x2);
      const maxX = Math.max(mlt.x1, mlt.x2);
      if (minX <= d.x2 && maxX >= d.x1) {
        if (mlt.y1 > localBottomY) localBottomY = mlt.y1;
        if (mlt.y2 > localBottomY) localBottomY = mlt.y2;
      }
    });
    if (localBottomY > 0) {
      d.y = localBottomY + 40;
    }
  });

  // --- MANUAL OVERRIDES FOR VISUAL CONNECTIONS ---
  const addManualConnection = (fromStn, fromLine, toStn, toLine) => {
    const leA = lineEnds[`${fromStn}-SEQ-${fromLine}`] || lineEnds[`${fromStn}-LINE-${fromLine}`];
    const leB = lineEnds[`${toStn}-SEQ-${toLine}`] || lineEnds[`${toStn}-LINE-${toLine}`];

    if (leA && leB) {
      let startX, startY = leA.y;
      let endX, endY = leB.y;

      if (leB.leftX > leA.rightX) {
        startX = leA.rightX; endX = leB.leftX;
      } else {
        startX = leA.leftX; endX = leB.rightX;
      }

      const midX = (startX + endX) / 2;
      const midY = (startY + endY) / 2;
      const path = `M ${startX} ${startY} L ${midX} ${midY} L ${endX} ${endY}`;

      data.connections.push({
        rawConn: {},
        path,
        startX, startY, endX, endY,
        color: '#ea580c',
        isLeftToRight: startX < endX,
        isBidirectional: false,
        isMainLineConnection: false,
        isRedundantMainLine: false,
        label: `${leA.label} → ${leB.label}`
      });
    }
  };

  addManualConnection('SGAC', 3, 'CDSL', 2);
  addManualConnection('CDSL', 2, 'DXD', 3);

  return data;
}